# Generated by Django 6.0.2 on 2026-02-18 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='matchday',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
