# Generated by Django 6.0.2 on 2026-02-18 16:05

import tipping.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipping', '0002_match_matchday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='prediction',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='group',
            name='join_code',
            field=models.CharField(db_index=True, default=tipping.models.generate_join_code, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='pred_away',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='pred_home',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.UniqueConstraint(fields=('user', 'group'), name='unique_user_group_membership'),
        ),
        migrations.AddConstraint(
            model_name='prediction',
            constraint=models.UniqueConstraint(fields=('user', 'group', 'match'), name='unique_prediction'),
        ),
    ]
