# Generated by Django 6.0.2 on 2026-02-19 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipping', '0005_groupmembership_is_creator_groupmembership_joined_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='autumn_champion',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='tournament',
            name='champion',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='tournament',
            name='first_coach_sacked',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='tournament',
            name='relegated_teams',
            field=models.TextField(blank=True, help_text='Kommagetrennte Liste der Absteiger'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='season_start',
            field=models.DateTimeField(blank=True, help_text='Ab diesem Zeitpunkt sind Bonustipps gesperrt.', null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='top_scorer',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='BonusPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_type', models.CharField(choices=[('herbstmeister', 'Herbstmeister'), ('meister', 'Meister'), ('trainer_first', 'Erste Trainerentlassung'), ('topscorer', 'Torschützenkönig'), ('relegation', 'Absteiger')], max_length=50)),
                ('value', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_predictions', to='tipping.group')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_predictions', to='tipping.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'group', 'bonus_type'), name='unique_bonus_prediction_per_group')],
            },
        ),
    ]
