# Generated by Django 6.0.2 on 2026-02-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipping', '0006_tournament_autumn_champion_tournament_champion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusprediction',
            name='bonus_type',
            field=models.CharField(choices=[('herbstmeister', 'Herbstmeister'), ('meister', 'Meister'), ('trainer_first', 'Erste Trainerentlassung'), ('topscorer', 'Torschützenkönig'), ('relegation1', 'Absteiger 1'), ('relegation2', 'Absteiger 2')], max_length=50),
        ),
    ]
