# Generated by Django 6.0.7 on 2026-07-23 05:04

import django.core.validators
import django.db.models.deletion
import tipping.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipping', '0009_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusprediction',
            name='tournament',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='bonus_predictions', to='tipping.tournament'),
        ),
        migrations.AlterField(
            model_name='bonusprediction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_predictions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='join_code',
            field=models.CharField(default=tipping.models.generate_join_code, max_length=24, unique=True, validators=[django.core.validators.MinLengthValidator(12)]),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='matchday',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='pred_away',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='pred_home',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, max_length=255, upload_to=tipping.models.avatar_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'webp')), tipping.models.validate_avatar_file]),
        ),
        migrations.AddConstraint(
            model_name='bonusprediction',
            constraint=models.CheckConstraint(condition=models.Q(('bonus_type__in', ('herbstmeister', 'meister', 'trainer_first', 'topscorer', 'relegation1', 'relegation2'))), name='bonus_type_is_valid'),
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_creator', True)), fields=('group',), name='one_creator_per_group'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('matchday__isnull', True), models.Q(('matchday__gte', 1), ('matchday__lte', 200)), _connector='OR'), name='match_md_positive_or_null'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('home_score__isnull', True), models.Q(('home_score__gte', 0), ('home_score__lte', 30)), _connector='OR'), name='match_home_score_0_30'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('away_score__isnull', True), models.Q(('away_score__gte', 0), ('away_score__lte', 30)), _connector='OR'), name='match_away_score_0_30'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('home_score__isnull', True), ('away_score__isnull', True)), models.Q(('home_score__isnull', False), ('away_score__isnull', False)), _connector='OR'), name='match_result_both_or_none'),
        ),
        migrations.AddConstraint(
            model_name='prediction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('pred_home__isnull', True), ('pred_away__isnull', True)), models.Q(('pred_home__isnull', False), ('pred_away__isnull', False)), _connector='OR'), name='prediction_scores_both_or_none'),
        ),
        migrations.AddConstraint(
            model_name='prediction',
            constraint=models.CheckConstraint(condition=models.Q(('pred_home__isnull', True), models.Q(('pred_home__gte', 0), ('pred_home__lte', 30)), _connector='OR'), name='prediction_home_0_30'),
        ),
        migrations.AddConstraint(
            model_name='prediction',
            constraint=models.CheckConstraint(condition=models.Q(('pred_away__isnull', True), models.Q(('pred_away__gte', 0), ('pred_away__lte', 30)), _connector='OR'), name='prediction_away_0_30'),
        ),
        migrations.AddConstraint(
            model_name='prediction',
            constraint=models.CheckConstraint(condition=models.Q(('points__isnull', True), models.Q(('points__gte', 0), ('points__lte', 4)), _connector='OR'), name='prediction_points_0_4'),
        ),
    ]
