# Generated by Django 6.0.7 on 2026-07-27 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipping', '0010_alter_bonusprediction_tournament_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
    ]
