# Generated by Django 6.0.7 on 2026-07-27 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipping', '0011_remove_userprofile_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_points', models.PositiveIntegerField(default=0)),
                ('bonus_points', models.PositiveIntegerField(default=0)),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('exact_predictions', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='tipping.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tip_group_standings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['group', '-total_points', 'user'], name='standing_group_total_idx')],
                'constraints': [models.UniqueConstraint(fields=('group', 'user'), name='uniq_group_user_standing')],
            },
        ),
        migrations.CreateModel(
            name='MatchdayScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchday', models.PositiveSmallIntegerField()),
                ('points', models.PositiveIntegerField(default=0)),
                ('exact_predictions', models.PositiveIntegerField(default=0)),
                ('cumulative_points', models.PositiveIntegerField(default=0)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_change', models.SmallIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchday_scores', to='tipping.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tip_matchday_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['group', 'matchday', 'rank'], name='score_group_md_rank_idx'), models.Index(fields=['group', 'user', 'matchday'], name='score_group_user_md_idx')],
                'constraints': [models.UniqueConstraint(fields=('group', 'user', 'matchday'), name='uniq_group_user_matchday')],
            },
        ),
    ]
