# Generated by Django 6.0.7 on 2026-07-27 16:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipping', '0012_groupstanding_matchdayscore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='groupstanding',
            index=models.Index(fields=['group', '-match_points', 'user'], name='standing_group_match_idx'),
        ),
    ]
