# Generated by Django 6.0.7 on 2026-07-28 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipping', '0013_add_match_points_standing_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandingRebuildJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affected_matchdays', models.JSONField(default=list)),
                ('match_ids', models.JSONField(default=list)),
                ('rebuild_bonus', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('running', 'Wird verarbeitet'), ('completed', 'Abgeschlossen'), ('failed', 'Fehlgeschlagen')], default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('processed_groups', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standing_rebuild_jobs', to='tipping.tournament')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='job_status_created_idx'), models.Index(fields=['tournament', 'status'], name='job_tournament_status_idx')],
            },
        ),
    ]
