# Generated by Django 6.0.7 on 2026-07-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipping', '0014_add_standing_rebuild_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='standingrebuildjob',
            name='group_ids',
            field=models.JSONField(default=list),
        ),
    ]
