# Generated by Django 6.0.7 on 2026-09-11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tipping",
            "0015_add_group_scope_to_standing_jobs",
        ),
        migrations.swappable_dependency(
            settings.AUTH_USER_MODEL
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="tip_reminders_enabled",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Der Nutzer erhält Erinnerungen für "
                    "noch nicht getippte Spiele."
                ),
            ),
        ),
        migrations.CreateModel(
            name="TipReminderDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        auto_now_add=True,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=(
                            django.db.models.deletion.CASCADE
                        ),
                        related_name=(
                            "tip_reminder_deliveries"
                        ),
                        to="tipping.group",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=(
                            django.db.models.deletion.CASCADE
                        ),
                        related_name=(
                            "tip_reminder_deliveries"
                        ),
                        to="tipping.match",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=(
                            django.db.models.deletion.CASCADE
                        ),
                        related_name=(
                            "tip_reminder_deliveries"
                        ),
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=[
                            "match",
                            "sent_at",
                        ],
                        name="reminder_match_sent_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "user",
                            "group",
                            "match",
                        ),
                        name=(
                            "uniq_tip_reminder_delivery"
                        ),
                    ),
                ],
            },
        ),
    ]
