# Generated by Django 6.0.7 on 2026-09-12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "tipping",
            "0019_groupmembership_status",
        ),
        migrations.swappable_dependency(
            settings.AUTH_USER_MODEL
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountRetentionNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inactivity_since",
                    models.DateTimeField(),
                ),
                (
                    "first_warning_claimed_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "first_warning_sent_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "final_warning_claimed_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "final_warning_sent_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=(
                            django.db.models.deletion.CASCADE
                        ),
                        related_name=(
                            "account_retention_notice"
                        ),
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=(
                            models.Q(
                                (
                                    "final_warning_sent_at__isnull",
                                    True,
                                )
                            )
                            |
                            models.Q(
                                (
                                    "first_warning_sent_at__isnull",
                                    False,
                                )
                            )
                        ),
                        name=(
                            "retention_final_requires_first"
                        ),
                    ),
                ],
            },
        ),
    ]
