# Generated by Django 6.0.8 on 2026-09-13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "tipping",
            "0020_accountretentionnotice",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="plan",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("plus", "Plus"),
                    ("club", "Club"),
                ],
                db_index=True,
                default="free",
                help_text=(
                    "Tarif der Gruppe. Bezahlte Tarife werden "
                    "vorerst ausschließlich manuell im Admin "
                    "vergeben."
                ),
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="plan_expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text=(
                    "Optionales Ablaufdatum. Danach gelten "
                    "automatisch wieder die "
                    "Free-Berechtigungen."
                ),
                null=True,
            ),
        ),
    ]
