# Generated by Django 6.0.8 on 2026-09-13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "tipping",
            "0021_group_plans",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmembership",
            name="is_co_admin",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Darf bei einem wirksamen Plus- oder Club-Plan "
                    "die laufende Gruppenverwaltung übernehmen."
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="groupmembership",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(is_creator=False)
                    | models.Q(is_co_admin=False)
                ),
                name="creator_is_not_group_co_admin",
            ),
        ),
        migrations.AddConstraint(
            model_name="groupmembership",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(is_active=True)
                    | models.Q(is_co_admin=False)
                ),
                name="inactive_membership_is_not_co_admin",
            ),
        ),
    ]
