# Generated by Django 6.0.8 on 2026-09-14 01:54

import django.core.validators
import django.db.models.deletion
import tipping.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipping', '0022_groupmembership_co_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, max_length=255, upload_to=tipping.models.group_logo_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'webp')), tipping.models.validate_group_logo])),
                ('primary_color', models.CharField(choices=[('blue', 'Azul'), ('green', 'Verde'), ('orange', 'Naranja'), ('red', 'Rojo'), ('violet', 'Violeta')], default='blue', max_length=12)),
                ('accent_color', models.CharField(choices=[('blue', 'Azul'), ('green', 'Verde'), ('orange', 'Naranja'), ('red', 'Rojo'), ('violet', 'Violeta')], default='violet', max_length=12)),
                ('welcome_text', models.CharField(blank=True, help_text='Kurzer Begrüßungstext auf dem Dashboard.', max_length=280)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='tipping.group')),
            ],
        ),
    ]
