# Generated by Django 6.0.8 on 2026-09-14 03:33

import django.core.validators
import tipping.models
from django.db import migrations, models


COLOR_TO_HEX = {
    "blue": "#438CFF",
    "green": "#2FBF83",
    "orange": "#E88A2D",
    "red": "#E45C72",
    "violet": "#8A67E8",
}


def convert_palette_colors_to_hex(apps, schema_editor):
    GroupBranding = apps.get_model("tipping", "GroupBranding")

    for branding in GroupBranding.objects.all().iterator():
        branding.primary_color = COLOR_TO_HEX.get(
            branding.primary_color,
            "#438CFF",
        )
        branding.accent_color = COLOR_TO_HEX.get(
            branding.accent_color,
            "#7257E8",
        )
        branding.save(
            update_fields=["primary_color", "accent_color"]
        )


def convert_hex_colors_to_palette(apps, schema_editor):
    GroupBranding = apps.get_model("tipping", "GroupBranding")
    hex_to_color = {
        value: key
        for key, value in COLOR_TO_HEX.items()
    }

    for branding in GroupBranding.objects.all().iterator():
        branding.primary_color = hex_to_color.get(
            branding.primary_color.upper(),
            "blue",
        )
        branding.accent_color = hex_to_color.get(
            branding.accent_color.upper(),
            "violet",
        )
        branding.save(
            update_fields=["primary_color", "accent_color"]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('tipping', '0023_groupbranding'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupbranding',
            name='background_color',
            field=models.CharField(default='#183153', max_length=7, validators=[django.core.validators.RegexValidator(message='Introduce un color hexadecimal válido.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='groupbranding',
            name='brand_intensity',
            field=models.CharField(choices=[('subtle', 'Sutil'), ('normal', 'Normal'), ('strong', 'Intensa')], default='normal', max_length=8),
        ),
        migrations.AddField(
            model_name='groupbranding',
            name='hero_image',
            field=models.ImageField(blank=True, max_length=255, upload_to=tipping.models.group_hero_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'webp')), tipping.models.validate_group_hero]),
        ),
        migrations.AddField(
            model_name='groupbranding',
            name='theme_mode',
            field=models.CharField(choices=[('dark', 'Oscuro'), ('light', 'Claro')], default='dark', max_length=8),
        ),
        migrations.AlterField(
            model_name='groupbranding',
            name='accent_color',
            field=models.CharField(default='#7257E8', max_length=7, validators=[django.core.validators.RegexValidator(message='Introduce un color hexadecimal válido.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AlterField(
            model_name='groupbranding',
            name='primary_color',
            field=models.CharField(default='#438CFF', max_length=7, validators=[django.core.validators.RegexValidator(message='Introduce un color hexadecimal válido.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.RunPython(
            convert_palette_colors_to_hex,
            convert_hex_colors_to_palette,
        ),
    ]
