# Generated by Django 6.0.8 on 2026-09-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipping', '0024_expand_group_branding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupbranding',
            name='theme_mode',
            field=models.CharField(choices=[('dark', 'Oscuro'), ('light', 'Claro')], default='light', max_length=8),
        ),
    ]
