# Generated by Django 6.0.8 on 2026-09-15 00:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


STAGE_DEFINITIONS = (
    ("regular", "Fase regular", 1, 30),
    ("hexagonal_final", "Hexagonal final", 2, 10),
    ("cuadrangular", "Cuadrangular", 3, 6),
    (
        "hexagonal_descenso",
        "Hexagonal de descenso",
        4,
        10,
    ),
)


def create_default_stages(apps, schema_editor):
    Tournament = apps.get_model("tipping", "Tournament")
    TournamentStage = apps.get_model(
        "tipping",
        "TournamentStage",
    )
    Match = apps.get_model("tipping", "Match")

    for tournament_id in (
        Tournament.objects.values_list("id", flat=True)
    ):
        stages = {}

        for code, name, sort_order, round_count in STAGE_DEFINITIONS:
            stage, _created = TournamentStage.objects.get_or_create(
                tournament_id=tournament_id,
                code=code,
                defaults={
                    "name": name,
                    "sort_order": sort_order,
                    "round_count": round_count,
                },
            )
            stages[code] = stage

        Match.objects.filter(
            tournament_id=tournament_id,
            stage__isnull=True,
        ).update(
            stage=stages["regular"],
            stage_round=models.F("matchday"),
        )


def remove_default_stages(apps, schema_editor):
    Match = apps.get_model("tipping", "Match")
    TournamentStage = apps.get_model(
        "tipping",
        "TournamentStage",
    )

    Match.objects.update(
        stage=None,
        stage_round=None,
    )
    TournamentStage.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tipping', '0025_light_branding_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='stage_round',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Rundennummer innerhalb der Phase. Die globale Spieltagsnummer bleibt separat erhalten.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.CreateModel(
            name='TournamentStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('regular', 'Fase regular'), ('hexagonal_final', 'Hexagonal final'), ('cuadrangular', 'Cuadrangular'), ('hexagonal_descenso', 'Hexagonal de descenso')], max_length=32)),
                ('name', models.CharField(max_length=80)),
                ('sort_order', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('round_count', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)])),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='tipping.tournament')),
            ],
            options={
                'ordering': ('tournament_id', 'sort_order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='match',
            name='stage',
            field=models.ForeignKey(blank=True, help_text='Wettbewerbsphase innerhalb der Saison. Ohne Auswahl wird das Spiel wie ein reguläres Saisonspiel behandelt.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='matches', to='tipping.tournamentstage'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['tournament', 'stage', 'stage_round'], name='match_tourn_stage_round_idx'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('stage_round__isnull', True), models.Q(('stage_round__gte', 1), ('stage_round__lte', 200)), _connector='OR'), name='match_stage_round_positive_or_null'),
        ),
        migrations.AddConstraint(
            model_name='tournamentstage',
            constraint=models.UniqueConstraint(fields=('tournament', 'code'), name='uniq_tournament_stage_code'),
        ),
        migrations.AddConstraint(
            model_name='tournamentstage',
            constraint=models.CheckConstraint(condition=models.Q(('round_count__gte', 1), ('round_count__lte', 200)), name='stage_round_count_1_200'),
        ),
        migrations.RunPython(
            create_default_stages,
            remove_default_stages,
        ),
    ]
